### PR TITLE
Allow users to install from luarocks

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
Solves #14

**Comment by mauricioabreu** [comment]
I think there are some things that you will need to do:
1) create a tag `v1.0` (change as you wish)
2) publish it using your `luarocks` account: https://github.com/luarocks/luarocks/wiki/Creating-a-rock#publishing-your-code-online

`luarocks` is like another package index. Names are uniques and `lua-resty-resolver` does not exist yet. If you don't have time to publish it,  do you allow me to publish it?

**Comment by mauricioabreu** [comment]
obs.: I am still testing it but it seems to work.

**Comment by jkeys089** [comment]
@mauricioabreu LGTM -- I'd like to keep the same version as https://opm.openresty.org/package/jkeys089/lua-resty-resolver/ though. If you could please update the PR to remove the version change I'll merge and publish to luarocks.

**Comment by mauricioabreu** [comment]
@jkeys089 done. `luarocks` need a `-1` in the version. Sorry!

**Pull request merged**
